apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-pipeline-scheduler
spec:
  schedule: "*/5 * * * *" # 5分ごとに実行（テスト用）
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: true # Suspend the CronJob
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: job-pipeline-sa # ServiceAccount を指定
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  # ランダムな識別子を生成
                  RANDOM_ID=$(head /dev/urandom | tr -dc a-z0-9 | head -c 6 || echo "default")

                  # PipelineRunマニフェストを作成して適用
                  cat <<EOF | kubectl create -f -
                  apiVersion: tekton.dev/v1beta1
                  kind: PipelineRun
                  metadata:
                    name: job-pipeline-run-${RANDOM_ID}
                  spec:
                    pipelineRef:
                      name: job-pipeline
                  EOF

                  echo "Created PipelineRun: job-pipeline-run-${RANDOM_ID}"
          restartPolicy: Never
