apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-pipeline-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-pipeline-role
  namespace: default
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-pipeline-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-pipeline-sa
    namespace: default
roleRef:
  kind: Role
  name: job-pipeline-role
  apiGroup: rbac.authorization.k8s.io
